services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
  backend:
    image: suslocal/sus-backend:2.0.0
    ports:
      - 8080:8080
    environment:
      - DB_HOST=db